### ISSUE TITLE
扩展启动一段时间后，内存占用飙高

### ISSUE THREAD

**Issue by twio142** [DIYgod/RSSHub-Radar#694]
扩展刚启动时占用内存仅 20+ MB，但几天后会发现飙高到 400+ MB，甚至期间并没使用过扩展。

![image](https://user-images.githubusercontent.com/64556708/165004224-d3940ae3-bcc2-4a5c-91f8-f0ae24ccd5d4.png)

Chrome: 99.0
RSSHub Radar: v1.7.0

**Comment by Rongronggg9** [comment]
Need more debug info:
- `chrome://process-internals/#web-contents`
- ![](https://user-images.githubusercontent.com/15956627/168478166-f3942085-1903-4764-974c-e18d2f85e34c.png)
- `chrome://extensions/?id=kefjpfngnndepjbopdmoebkipbgkggaa` -> click `background.html` -> switch to the `Console` tab
![](https://user-images.githubusercontent.com/15956627/168478324-2c5b26a7-635c-4320-ab1b-6bbed9871d37.png)

**Comment by twio142** [comment]
![image](https://user-images.githubusercontent.com/64556708/208107413-c92a6bd6-903d-4408-b028-4d29a7c73027.png)

我也有使用标签页定时休眠的插件。另外我发现每当打开新标签页（chrome://newtab）就会报错 `Failed to construct 'URL': Invalid URL` 和 `Cannot read properties of undefined (reading 'length')`

**Comment by JJcdomat** [comment]
使用休眠标签导致内存异常的可以试试右键标签改了。

**Comment by DIYgod** [comment]
Invalid URL errors are fixed in cf15a0a66a6da8576610f8a0331525e542435727, but I'm not sure if it caused the memory leak

**Comment by Chaoses-Ib** [comment]
![image](https://user-images.githubusercontent.com/50246090/231787265-4cecef13-ab58-4424-b280-d976beea0872.png)

This problem still exists.

Edge: 111.0.1661.62 x64
RSSHub Radar: 1.10.1

**Comment by lesywix** [comment]
Same issue on version v2.0.6
Chrome: 120.0.6099.109 (x86_64)

**Comment by DIYgod** [comment]
I speculate that the memory leak in the v2 version is caused by console.debug. I have removed all console.x at [here](9caee299f5af3293d88dc1c25cce23fd2a444138). Please observe if v2.0.7 still has any memory issues.

**Comment by DIYgod** [comment]
In version 2.0.7, the memory consumption is still high, but the background service worker and offscreen.html memory usage seems to be normal. I'm unsure about the exact cause of the problem.

**Comment by DIYgod** [comment]
I further debugged and found that the memory leak may be caused by DOMParser. Then I found a [stackoverflow post](
https://stackoverflow.com/questions/56451731/dom-parser-chrome-extension-memory-leak) confirming my guess, so I removed DOMParser in this commit, hoping this will solve the problem. 653f0db98751f0ae380105c32b8d27a94b1062e0
